=== cafeteru/Web/SEW/p2/Ejercicio-1/Tarea-4/tarea4.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="uo239795" xmlns="uo239795"
           elementFormDefault="qualified">
    <xs:element name="articulos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="autores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="autor" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombreAutor" type="xs:string"/>
                                                    <xs:element name="correo" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="resumen" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="claves">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="clave" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="revista" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="enumeracionRevista">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="numeroRevista" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="volumenRevista" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="paginaInicio" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="paginaFinal" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="aÃ±o" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minExclusive value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cafeteru/Web/public_html/SEW/p2/Ejercicio-1/Tarea-4/tarea4.xml
<?xml version="1.0" encoding="UTF-8"?>
<articulos xmlns="uo239795" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="uo239795 tarea4.xsd">
    <articulo>
        <titulo>
            Midgar: Detection of people through computer vision in the Internet of Things scenarios to improve the
            security in Smart Cities, Smart Towns, and Smart Homes.
        </titulo>
        <autores>
            <autor>
                <nombreAutor>Cristian González García</nombreAutor>
                <correo>gonzalezgarciacristian@hotmail.com</correo>
            </autor>
            <autor>
                <nombreAutor>Daniel Meana-Llorián</nombreAutor>
                <correo>danielmeanallorian@gmail.com</correo>
            </autor>
            <autor>
                <nombreAutor>B. Cristina Pelayo García-Bustelo</nombreAutor>
                <correo>crispelayo@uniovi.es</correo>
            </autor>
            <autor>
                <nombreAutor>Juan Manuel Cueva Lovelle</nombreAutor>
                <correo>cueva@uniovi.es</correo>
            </autor>
            <autor>
                <nombreAutor>Néstor García-Fernández</nombreAutor>
                <correo>nestor@uniovi.es</correo>
            </autor>
        </autores>
        <resumen>Could we use Computer Vision in the Internet of Things for using pictures as sensors? This is the
            principal hypothesis that we want to resolve. Currently, in order to create safety areas, cities, or homes,
            people use IP cameras. Nevertheless, this system needs people who watch the camera images, watch the
            recording after something occurred, or watch when the camera notifies them of any movement. These are the
            disadvantages. Furthermore, there are many Smart Cities and Smart Homes around the world. This is why we
            thought of using the idea of the Internet of Things to add a way of automating the use of IP cameras. In our
            case, we propose the analysis of pictures through Computer Vision to detect people in the analysed pictures.
            With this analysis, we are able to obtain if these pictures contain people and handle the pictures as if
            they were sensors with two possible states. Notwithstanding, Computer Vision is a very complicated field.
            This is why we needed a second hypothesis: Could we work with Computer Vision in the Internet of Things with
            a good accuracy to automate or semi-automate this kind of events? The demonstration of these hypotheses
            required a testing over our Computer Vision module to check the possibilities that we have to use this
            module in a possible real environment with a good accuracy. Our proposal, as a possible solution, is the
            analysis of entire sequence instead of isolated pictures for using pictures as sensors in the Internet of
            Things.
        </resumen>
        <claves>
            <clave>Smart Cities</clave>
            <clave>Smart Towns</clave>
            <clave>Smart Homes</clave>
            <clave>Internet of Things</clave>
            <clave>Smart Objects</clave>
            <clave>Computer Vision</clave>
            <clave>Surveillance</clave>
            <clave>Security</clave>
        </claves>
        <revista>Future Generation Comp. Syst</revista>
        <enumeracionRevista>
            <volumenRevista>76</volumenRevista>
        </enumeracionRevista>
        <paginaInicio>275</paginaInicio>
        <paginaFinal>284</paginaFinal>
        <año>2017</año>
    </articulo>
    <articulo>
        <titulo>A review about Smart Objects, Sensors, and Actuators.</titulo>
        <autores>
            <autor>
                <nombreAutor>Cristian González García</nombreAutor>
                <correo>gonzalezgarciacristian@hotmail.com</correo>
            </autor>
            <autor>
                <nombreAutor>Daniel Meana-Llorián</nombreAutor>
                <correo>danielmeanallorian@gmail.com</correo>
            </autor>
            <autor>
                <nombreAutor>B. Cristina Pelayo García-Bustelo</nombreAutor>
                <correo>crispelayo@uniovi.es</correo>
            </autor>
            <autor>
                <nombreAutor>Juan Manuel Cueva Lovelle</nombreAutor>
                <correo>cueva@uniovi.es</correo>
            </autor>
            <autor>
                <nombreAutor>Néstor García-Fernández</nombreAutor>
                <correo>nestor@uniovi.es</correo>
            </autor>
        </autores>
        <resumen>Smart Objects and the Internet of Things are two ideas which describe the future, walk together, and
            complement each other. Thus, the interconnection among objects can make them more intelligent or expand
            their intelligence to unsuspected limits. This could be achieved with a new network that interconnects each
            object around the world. However, to achieve this goal, the objects need a network that supports
            heterogeneous and ubiquitous objects, a network where exists more traffic among objects than among humans,
            but supporting for both types. For these reasons, both concepts are very close. Cities, houses, cars,
            machines, or any another object that can sense, respond, work, or make easier the lives of their owner. This
            is a part of the future, an immediate future. Notwithstanding, first of all, there are to resolve a series
            of problems. The most important problem is the heterogeneity of objects. This article is going to show a
            theoretical frame and the related work about Smart Object. The article will explain what are Smart Objects,
            doing emphasis in their difference with Not- Smart Objects. After, we will present one of the different
            object classification system, in our opinion, the most complete.
        </resumen>
        <claves>
            <clave>Actuator</clave>
            <clave>Internet of things</clave>
            <clave>Sensor</clave>
            <clave>SmartCities</clave>
        </claves>
        <revista>IJIMAI</revista>
        <enumeracionRevista>
            <numeroRevista>4</numeroRevista>
        </enumeracionRevista>
        <paginaInicio>7</paginaInicio>
        <paginaFinal>10</paginaFinal>
        <año>2017</año>
    </articulo>
    <articulo>
        <titulo>SenseQ: Replying questions of Social Networks users by using a Wireless Sensor Network based on sensor
            relationships
        </titulo>
        <autores>
            <autor>
                <nombreAutor>Cristian González García</nombreAutor>
                <correo>gonzalezgarciacristian@hotmail.com</correo>
            </autor>
            <autor>
                <nombreAutor>Daniel Meana-Llorián</nombreAutor>
                <correo>danielmeanallorian@gmail.com</correo>
            </autor>
            <autor>
                <nombreAutor>B. Cristina Pelayo García-Bustelo</nombreAutor>
                <correo>crispelayo@uniovi.es</correo>
            </autor>
            <autor>
                <nombreAutor>Vicente García Díaz</nombreAutor>
                <correo>garciavicente@uniovi.es</correo>
            </autor>
            <autor>
                <nombreAutor>Néstor García-Fernández</nombreAutor>
                <correo>nestor@uniovi.es</correo>
            </autor>
        </autores>
        <resumen>Social Networks are a way of establishing communications with friends or family and a way of knowing
            what happens around us. However, there are not machines that provide users with information about their
            worries. What happens if a user wants to know if it is raining in a specific place at that moment? He needs
            to ask a person who is in that place at that moment. Why not take advantage of the Internet of Things to
            collect information in real time and answer users questions? The Internet of Things is a field that tries to
            measure everything by gathering data from sensors and interconnect different objects. Why not combine Social
            Networks and the Internet of Things? In this paper, we propose the development of a new system that will
            allow users to ask for information to a network of sensors through Social Networks, concretely in this case
            through Twitter. The system will have sensors registered by different users and this system that will be
            used to answer questions of other users. The system will be able to collect information of users sensors,
            process it, and use it to answer users questions through Social Networks. In order to gather the data from
            sensors and combine them, we propose three dierent types of relationships between sensors: neighboring
            relationship, familiar relationship and working relationship. Besides, we propose an architecture based on
            three layers: social layer, backend layer and object layer.
        </resumen>
        <claves>
            <clave>Social Networks</clave>
            <clave>Sensors</clave>
            <clave>The Internet of Things</clave>
            <clave>Twitter</clave>
            <clave>WSN</clave>
        </claves>
        <revista>ACM</revista>
        <enumeracionRevista>
            <numeroRevista>8</numeroRevista>
        </enumeracionRevista>
        <paginaInicio>1</paginaInicio>
        <paginaFinal>23</paginaFinal>
        <año>2016</año>
    </articulo>
    <articulo>
        <titulo>Swift vs. Objective-C: A New Programming Language</titulo>
        <autores>
            <autor>
                <nombreAutor>Cristian González García</nombreAutor>
                <correo>gonzalezgarciacristian@hotmail.com</correo>
            </autor>
            <autor>
                <nombreAutor>Daniel Meana-Llorián</nombreAutor>
                <correo>danielmeanallorian@gmail.com</correo>
